/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author demib
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        cargarLogo();
        

        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlBtns = new javax.swing.JPanel();
        btnRegistrarVoluntario = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnRegistrarRefugio = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnRegistrarAnimal = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnDocumentarTarea = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnSalir = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlSidebar.setBackground(new java.awt.Color(255, 255, 255));

        pnlLogo.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogo.setMaximumSize(new java.awt.Dimension(200, 150));
        pnlLogo.setMinimumSize(new java.awt.Dimension(200, 150));
        pnlLogo.setPreferredSize(new java.awt.Dimension(200, 150));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
        );

        pnlBtns.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtns.setLayout(new javax.swing.BoxLayout(pnlBtns, javax.swing.BoxLayout.Y_AXIS));

        btnRegistrarVoluntario.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarVoluntario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrarVoluntario.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarVoluntario.setText("Registrar Voluntario");
        btnRegistrarVoluntario.setBorder(null);
        btnRegistrarVoluntario.setBorderPainted(false);
        btnRegistrarVoluntario.setFocusable(false);
        btnRegistrarVoluntario.setMaximumSize(new java.awt.Dimension(212, 40));
        btnRegistrarVoluntario.setPreferredSize(new java.awt.Dimension(180, 40));
        btnRegistrarVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVoluntarioActionPerformed(evt);
            }
        });
        pnlBtns.add(btnRegistrarVoluntario);
        pnlBtns.add(filler1);

        btnRegistrarRefugio.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarRefugio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrarRefugio.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarRefugio.setText("Registrar Refugio");
        btnRegistrarRefugio.setBorder(null);
        btnRegistrarRefugio.setBorderPainted(false);
        btnRegistrarRefugio.setFocusable(false);
        btnRegistrarRefugio.setMaximumSize(new java.awt.Dimension(212, 40));
        btnRegistrarRefugio.setPreferredSize(new java.awt.Dimension(180, 40));
        pnlBtns.add(btnRegistrarRefugio);
        pnlBtns.add(filler2);

        btnRegistrarAnimal.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarAnimal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrarAnimal.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarAnimal.setText("Registrar Animal");
        btnRegistrarAnimal.setBorder(null);
        btnRegistrarAnimal.setBorderPainted(false);
        btnRegistrarAnimal.setFocusable(false);
        btnRegistrarAnimal.setMaximumSize(new java.awt.Dimension(212, 40));
        btnRegistrarAnimal.setPreferredSize(new java.awt.Dimension(180, 40));
        pnlBtns.add(btnRegistrarAnimal);
        pnlBtns.add(filler3);

        btnDocumentarTarea.setBackground(new java.awt.Color(255, 255, 255));
        btnDocumentarTarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDocumentarTarea.setForeground(new java.awt.Color(0, 0, 0));
        btnDocumentarTarea.setText("Documentar Tarea");
        btnDocumentarTarea.setBorder(null);
        btnDocumentarTarea.setBorderPainted(false);
        btnDocumentarTarea.setFocusable(false);
        btnDocumentarTarea.setMaximumSize(new java.awt.Dimension(212, 40));
        btnDocumentarTarea.setPreferredSize(new java.awt.Dimension(180, 40));
        pnlBtns.add(btnDocumentarTarea);
        pnlBtns.add(filler5);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusable(false);
        btnSalir.setMaximumSize(new java.awt.Dimension(212, 40));
        btnSalir.setPreferredSize(new java.awt.Dimension(180, 40));
        pnlBtns.add(btnSalir);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBtns, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(pnlBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenido.setPreferredSize(new java.awt.Dimension(776, 776));

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVoluntarioActionPerformed
        // TODO add your handling code here:
        
        
        pnlContenido.setLayout(new java.awt.BorderLayout());

        pnlContenido.add(new FrmVoluntario(), java.awt.BorderLayout.CENTER);

        pnlContenido.revalidate();
        
        
    }//GEN-LAST:event_btnRegistrarVoluntarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocumentarTarea;
    private javax.swing.JButton btnRegistrarAnimal;
    private javax.swing.JButton btnRegistrarRefugio;
    private javax.swing.JButton btnRegistrarVoluntario;
    private javax.swing.JButton btnSalir;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlBtns;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlSidebar;
    // End of variables declaration//GEN-END:variables

    private void cargarLogo() {
    Icon logoIcon = new ImageIcon(new ImageIcon(getClass().getResource("/images/logo.png")).getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), 0));
    
    lblLogo.setIcon(logoIcon);
    
    
}

}
