/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.*;
import dao.*;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import models.*;

/**
 *
 * @author demib
 */
public class FrmTarea3 extends javax.swing.JPanel {
private TareaController tareaController;
    /**
     * Creates new form FrmVoluntario
     */
    public FrmTarea3() {
    tareaController = new TareaController(new TareaDAO());
    registrarTarea();
    initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistroVoluntario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombreVoluntario = new javax.swing.JTextField();
        lblRelleneCampos = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtNombreAnimal = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtActividad = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        spinnerDia = new javax.swing.JSpinner();
        lblDia = new javax.swing.JLabel();
        spinnerMes = new javax.swing.JSpinner();
        lblMes = new javax.swing.JLabel();
        lblanio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(776, 776));

        lblRegistroVoluntario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRegistroVoluntario.setText("Registro de Tareas");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre.setText("Nombre del voluntario:");

        txtNombreVoluntario.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreVoluntario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtNombreVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreVoluntarioActionPerformed(evt);
            }
        });

        lblRelleneCampos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRelleneCampos.setText("Rellene todos los campos.");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelefono.setText("Nombre del animal:");

        txtNombreAnimal.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreAnimal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtNombreAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAnimalActionPerformed(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCorreo.setText("Actividad:");

        txtActividad.setBackground(new java.awt.Color(255, 255, 255));
        txtActividad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActividadActionPerformed(evt);
            }
        });

        lblFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechaNacimiento.setText("Fecha :");

        lblEspecialidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEspecialidad.setText("Especialidad:");

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        spinnerDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        lblDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDia.setText("Dia:");

        spinnerMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        lblMes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMes.setText("Mes:");

        lblanio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblanio.setText("Año:");

        txtAnio.setBackground(new java.awt.Color(255, 255, 255));
        txtAnio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });

        txtEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        txtEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre)
                    .addComponent(txtNombreVoluntario, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(lblRelleneCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistroVoluntario)
                    .addComponent(lblTelefono)
                    .addComponent(txtNombreAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(lblCorreo)
                    .addComponent(txtActividad, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaNacimiento)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblanio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEspecialidad))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRegistroVoluntario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRelleneCampos)
                        .addGap(55, 55, 55)
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDia)
                            .addComponent(spinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMes)
                            .addComponent(spinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblanio)
                            .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(lblEspecialidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreVoluntarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreVoluntarioActionPerformed

    private void txtNombreAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAnimalActionPerformed

    private void txtActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActividadActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        registrarTarea();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistroVoluntario;
    private javax.swing.JLabel lblRelleneCampos;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblanio;
    private javax.swing.JSpinner spinnerDia;
    private javax.swing.JSpinner spinnerMes;
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtNombreAnimal;
    private javax.swing.JTextField txtNombreVoluntario;
    // End of variables declaration//GEN-END:variables

    
private void registrarTarea() {
   try {

        // 1️⃣ Obtener datos del formulario
        String nombreVoluntario = txtNombreVoluntario.getText().trim();
        String nombreAnimal = txtNombreAnimal.getText().trim();
        String actividad = txtActividad.getText().trim();

        int dia = (Integer) spinnerDia.getValue();
        int mes = (Integer) spinnerMes.getValue();
        int anio = Integer.parseInt(txtAnio.getText());

        LocalDate fecha = LocalDate.of(anio, mes, dia);

        if (nombreVoluntario.isEmpty() || nombreAnimal.isEmpty() || actividad.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Todos los campos son obligatorios.",
                    "Error",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // 2️⃣ Crear objetos básicos (solo con ID si ya los tienes)
        Voluntario voluntario = new Voluntario();
        voluntario.setIdVoluntario(1); // ⚠️ aquí deberías buscarlo por nombre en BD

        Animal animal = new Animal();
        animal.setIdAnimal(1); // ⚠️ igual aquí

        Refugio refugio = new Refugio();
        refugio.setIdRefugio(1); // ⚠️ igual aquí

        // 3️⃣ Mandar al controlador
        boolean exito = tareaController.agregarTarea(
                fecha.atStartOfDay(),
                actividad,
                voluntario,
                animal,
                refugio
        );

        // 4️⃣ Resultado
        if (exito) {
            JOptionPane.showMessageDialog(this, "Tarea registrada correctamente.");
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al registrar la tarea.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}
    
}
