/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.EspecialidadController;
import controllers.TareaController;
import controllers.VoluntarioController;
import dao.AnimalDAO;
import dao.EspecialidadDAO;
import dao.RefugioDAO;
import dao.VoluntarioDAO;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import controllers.TareaController;
import dao.AnimalDAO;
import dao.RefugioDAO;
import dao.TareaDAO;
import dao.VoluntarioDAO;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author demib
 */
public class FrmTarea extends javax.swing.JPanel {
    
      private TareaController tareaController;
    private VoluntarioDAO voluntarioDAO;
    private AnimalDAO animalDAO;
    private RefugioDAO refugioDAO;

    public FrmTarea() {
        initComponents();
        inicializarFormulario();
        tareaController = new TareaController(new TareaDAO());
        voluntarioDAO = new VoluntarioDAO();
        animalDAO = new AnimalDAO();
        refugioDAO = new RefugioDAO();
        cargarTareas();        
    }
    
    private void inicializarFormulario(){
        ocultarErrores();
    }
    
    private void ocultarErrores(){
        lblVoluntarioObligatorio.setVisible(false);
        lblAnimalObligatorio.setVisible(false);
        lblRefugioObligatorio.setVisible(false);
        lblActividadObligatorio.setVisible(false);
        lblAnioObligatorio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistroTareas = new javax.swing.JLabel();
        lblVoluntario = new javax.swing.JLabel();
        txtIdVoluntario = new javax.swing.JTextField();
        lblRelleneCampos = new javax.swing.JLabel();
        lblAnimal = new javax.swing.JLabel();
        txtIdAnimal = new javax.swing.JTextField();
        lblRefugio = new javax.swing.JLabel();
        txtIdRefugio = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        spinnerDia = new javax.swing.JSpinner();
        lblDia = new javax.swing.JLabel();
        spinnerMes = new javax.swing.JSpinner();
        lblMes = new javax.swing.JLabel();
        lblanio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        scrlPaneTarea = new javax.swing.JScrollPane();
        tblTarea = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        txtBarraBusqueda = new javax.swing.JTextField();
        lblVoluntarioObligatorio = new javax.swing.JLabel();
        lblAnimalObligatorio = new javax.swing.JLabel();
        lblRefugioObligatorio = new javax.swing.JLabel();
        lblAnioObligatorio = new javax.swing.JLabel();
        lblRelleneCampos1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        lblActividad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaActividad = new javax.swing.JTextArea();
        btnRegistrar = new javax.swing.JButton();
        lblActividadObligatorio = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(776, 776));

        lblRegistroTareas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRegistroTareas.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistroTareas.setText("Registro de Tarea");

        lblVoluntario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVoluntario.setForeground(new java.awt.Color(0, 0, 0));
        lblVoluntario.setText("ID Voluntario:");

        txtIdVoluntario.setBackground(new java.awt.Color(255, 255, 255));
        txtIdVoluntario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdVoluntario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIdVoluntario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdVoluntarioFocusLost(evt);
            }
        });
        txtIdVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVoluntarioActionPerformed(evt);
            }
        });

        lblRelleneCampos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRelleneCampos.setForeground(new java.awt.Color(0, 0, 0));
        lblRelleneCampos.setText("Rellene todos los campos.");

        lblAnimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAnimal.setForeground(new java.awt.Color(0, 0, 0));
        lblAnimal.setText("ID Animal:");

        txtIdAnimal.setBackground(new java.awt.Color(255, 255, 255));
        txtIdAnimal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdAnimal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtIdAnimal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdAnimalFocusLost(evt);
            }
        });
        txtIdAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAnimalActionPerformed(evt);
            }
        });

        lblRefugio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRefugio.setForeground(new java.awt.Color(0, 0, 0));
        lblRefugio.setText("ID Refugio: ");

        txtIdRefugio.setBackground(new java.awt.Color(255, 255, 255));
        txtIdRefugio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdRefugio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtIdRefugio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdRefugioFocusLost(evt);
            }
        });
        txtIdRefugio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdRefugioActionPerformed(evt);
            }
        });

        lblFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaNacimiento.setText("Fecha Nacimiento:");

        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        spinnerDia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spinnerDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        lblDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDia.setForeground(new java.awt.Color(0, 0, 0));
        lblDia.setText("Dia:");

        spinnerMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spinnerMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        lblMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMes.setForeground(new java.awt.Color(0, 0, 0));
        lblMes.setText("Mes:");

        lblanio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblanio.setForeground(new java.awt.Color(0, 0, 0));
        lblanio.setText("Año:");

        txtAnio.setBackground(new java.awt.Color(255, 255, 255));
        txtAnio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAnio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtAnio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnioFocusLost(evt);
            }
        });
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });

        tblTarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTareaMouseClicked(evt);
            }
        });
        scrlPaneTarea.setViewportView(tblTarea);

        lblId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        lblId.setText("Id:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtId.setText(" 00");
        txtId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("ELIMINAR");
        btnBorrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 2, true));
        btnBorrar.setBorderPainted(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        txtBarraBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        txtBarraBusqueda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBarraBusqueda.setToolTipText("");
        txtBarraBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtBarraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarraBusquedaActionPerformed(evt);
            }
        });
        txtBarraBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarraBusquedaKeyReleased(evt);
            }
        });

        lblVoluntarioObligatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVoluntarioObligatorio.setForeground(new java.awt.Color(255, 102, 102));
        lblVoluntarioObligatorio.setText("Campo obligatorio");

        lblAnimalObligatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAnimalObligatorio.setForeground(new java.awt.Color(255, 102, 102));
        lblAnimalObligatorio.setText("Campo obligatorio");

        lblRefugioObligatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRefugioObligatorio.setForeground(new java.awt.Color(255, 102, 102));
        lblRefugioObligatorio.setText("Campo obligatorio");

        lblAnioObligatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAnioObligatorio.setForeground(new java.awt.Color(255, 102, 102));
        lblAnioObligatorio.setText("Campo obligatorio");

        lblRelleneCampos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRelleneCampos1.setForeground(new java.awt.Color(0, 0, 0));
        lblRelleneCampos1.setText("TABLA DE CLIENTES");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Busca por : Actividad");

        btnActualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 2, true));
        btnActualizar.setBorderPainted(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblActividad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblActividad.setForeground(new java.awt.Color(0, 0, 0));
        lblActividad.setText("Actividad (Max: 50 caracteres.):");

        jTextAreaActividad.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaActividad.setColumns(20);
        jTextAreaActividad.setRows(5);
        jScrollPane1.setViewportView(jTextAreaActividad);

        btnRegistrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblActividadObligatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblActividadObligatorio.setForeground(new java.awt.Color(255, 102, 102));
        lblActividadObligatorio.setText("Campo obligatorio");

        btnAnterior.setText("ANTERIOR");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(lblVoluntario, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVoluntarioObligatorio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(lblFechaNacimiento)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblAnioObligatorio))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblDia)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(spinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblMes)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(spinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(lblanio)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblActividad)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblActividadObligatorio))
                                        .addComponent(lblRelleneCampos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblRegistroTareas, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtIdVoluntario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblAnimal)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblAnimalObligatorio))
                                        .addComponent(txtIdAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblRefugio)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblRefugioObligatorio))
                                        .addComponent(txtIdRefugio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrlPaneTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtBarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSiguiente))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRelleneCampos1)
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistroTareas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRelleneCampos)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVoluntario)
                    .addComponent(lblVoluntarioObligatorio)
                    .addComponent(lblRelleneCampos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrlPaneTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnterior)
                            .addComponent(btnSiguiente)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnimal)
                            .addComponent(lblAnimalObligatorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRefugio)
                            .addComponent(lblRefugioObligatorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblActividad)
                            .addComponent(lblActividadObligatorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaNacimiento)
                            .addComponent(lblAnioObligatorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDia)
                            .addComponent(spinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMes)
                            .addComponent(spinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblanio)
                            .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVoluntarioActionPerformed
        
    }//GEN-LAST:event_txtIdVoluntarioActionPerformed

    private void txtIdAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAnimalActionPerformed

    private void txtIdRefugioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdRefugioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRefugioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtBarraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarraBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarraBusquedaActionPerformed

    private void txtIdVoluntarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdVoluntarioFocusLost
        // TODO add your handling code here:
        validarTxtIdVoluntario();
    }//GEN-LAST:event_txtIdVoluntarioFocusLost

    private void txtIdAnimalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdAnimalFocusLost
        // TODO add your handling code here:
        validarTxtIdAnimal();
    }//GEN-LAST:event_txtIdAnimalFocusLost

    private void txtIdRefugioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdRefugioFocusLost
        // TODO add your handling code here:
        validarTxtIdRefugio();
    }//GEN-LAST:event_txtIdRefugioFocusLost

    private void txtAnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioFocusLost
        // TODO add your handling code here:
        validarFecha();
    }//GEN-LAST:event_txtAnioFocusLost

    private void txtBarraBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarraBusquedaKeyReleased
        // TODO add your handling code here:
        String texto = txtBarraBusqueda.getText();
        filtrarTabla(texto);
    }//GEN-LAST:event_txtBarraBusquedaKeyReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        registrarTarea();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void tblTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTareaMouseClicked
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_tblTareaMouseClicked

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaActividad;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JLabel lblActividadObligatorio;
    private javax.swing.JLabel lblAnimal;
    private javax.swing.JLabel lblAnimalObligatorio;
    private javax.swing.JLabel lblAnioObligatorio;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblRefugio;
    private javax.swing.JLabel lblRefugioObligatorio;
    private javax.swing.JLabel lblRegistroTareas;
    private javax.swing.JLabel lblRelleneCampos;
    private javax.swing.JLabel lblRelleneCampos1;
    private javax.swing.JLabel lblVoluntario;
    private javax.swing.JLabel lblVoluntarioObligatorio;
    private javax.swing.JLabel lblanio;
    private javax.swing.JScrollPane scrlPaneTarea;
    private javax.swing.JSpinner spinnerDia;
    private javax.swing.JSpinner spinnerMes;
    private javax.swing.JTable tblTarea;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtBarraBusqueda;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdAnimal;
    private javax.swing.JTextField txtIdRefugio;
    private javax.swing.JTextField txtIdVoluntario;
    // End of variables declaration//GEN-END:variables
   
    
    private void cargarTareas() {
        tblTarea.setModel(tareaController.obtenerTablaTareas());
    }
    
    private void cargarDatos() {
        int fila = tblTarea.getSelectedRow();
        if (fila >= 0) {
            txtId.setText(tblTarea.getValueAt(fila, 0).toString());
            txtIdVoluntario.setText(tblTarea.getValueAt(fila, 3).toString());
            txtIdAnimal.setText(tblTarea.getValueAt(fila, 4).toString());
            txtIdRefugio.setText(tblTarea.getValueAt(fila, 5).toString());
            jTextAreaActividad.setText(tblTarea.getValueAt(fila, 2).toString());

            String fechaStr = tblTarea.getValueAt(fila, 1).toString();
            try {
                LocalDateTime fecha = LocalDateTime.parse(fechaStr);
                spinnerDia.setValue(fecha.getDayOfMonth());
                spinnerMes.setValue(fecha.getMonthValue());
                txtAnio.setText(String.valueOf(fecha.getYear()));
            } catch (Exception e) {
                // si el formato no parsea directamente se deja como está
            }
        }
    }
    
    //Limpia las casillas
    private void limpiarCampos() {
        txtId.setText("00");
        txtIdVoluntario.setText("");
        txtIdAnimal.setText("");
        txtIdRefugio.setText("");
        jTextAreaActividad.setText("");
        txtAnio.setText("");
        spinnerDia.setValue(1);
        spinnerMes.setValue(1);
        ocultarErrores();
    }
    
    //Validacion  del campo de texto ID Voluntario
    public boolean validarTxtIdVoluntario() {
        String val = txtIdVoluntario.getText().trim();
        if (val.isEmpty()) {
            lblVoluntarioObligatorio.setText("Campo obligatorio");
            lblVoluntarioObligatorio.setVisible(true);
            txtIdVoluntario.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        if (!val.matches("\\d+")) {
            lblVoluntarioObligatorio.setText("Solo números");
            lblVoluntarioObligatorio.setVisible(true);
            txtIdVoluntario.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        if (voluntarioDAO.obtenerPorId(Integer.parseInt(val)) == null) {
            lblVoluntarioObligatorio.setText("ID no existe");
            lblVoluntarioObligatorio.setVisible(true);
            txtIdVoluntario.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        txtIdVoluntario.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        lblVoluntarioObligatorio.setVisible(false);
        return true;
    }
    
    //Validacion  del campo de texto ID Animal
    public boolean validarTxtIdAnimal() {
        String val = txtIdAnimal.getText().trim();
        if (val.isEmpty()) {
            lblAnimalObligatorio.setText("Campo obligatorio");
            lblAnimalObligatorio.setVisible(true);
            txtIdAnimal.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        if (!val.matches("\\d+")) {
            lblAnimalObligatorio.setText("Solo números");
            lblAnimalObligatorio.setVisible(true);
            txtIdAnimal.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        if (animalDAO.obtenerPorId(Integer.parseInt(val)) == null) {
            lblAnimalObligatorio.setText("ID no existe");
            lblAnimalObligatorio.setVisible(true);
            txtIdAnimal.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        txtIdAnimal.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        lblAnimalObligatorio.setVisible(false);
        return true;
    }
   
    //Validacion  del campo de texto ID Refugio
    public boolean validarTxtIdRefugio() {
        String val = txtIdRefugio.getText().trim();
        if (val.isEmpty()) {
            lblRefugioObligatorio.setText("Campo obligatorio");
            lblRefugioObligatorio.setVisible(true);
            txtIdRefugio.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        if (!val.matches("\\d+")) {
            lblRefugioObligatorio.setText("Solo números");
            lblRefugioObligatorio.setVisible(true);
            txtIdRefugio.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        if (refugioDAO.obtenerRefugioPorId(Integer.parseInt(val)) == null) {
            lblRefugioObligatorio.setText("ID no existe");
            lblRefugioObligatorio.setVisible(true);
            txtIdRefugio.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        txtIdRefugio.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        lblRefugioObligatorio.setVisible(false);
        return true;
    }
    

     //Validacion  del campo de texto Actividad   
    public boolean validarActividad() {
        String val = jTextAreaActividad.getText().trim();
        if (val.isEmpty()) {
            lblActividadObligatorio.setText("Campo obligatorio");
            lblActividadObligatorio.setVisible(true);
            jScrollPane1.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        if (val.length() > 50) {
            lblActividadObligatorio.setText("Máximo 50 caracteres");
            lblActividadObligatorio.setVisible(true);
            jScrollPane1.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        jScrollPane1.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        lblActividadObligatorio.setVisible(false);
        return true;
    }
    
    //Validacion  de la fecha
    public boolean validarFecha() {
        String anioStr = txtAnio.getText().trim();
        if (anioStr.isEmpty()) {
            lblAnioObligatorio.setText("Campo obligatorio");
            lblAnioObligatorio.setVisible(true);
            txtAnio.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        if (!anioStr.matches("\\d{4}")) {
            lblAnioObligatorio.setText("Año no válido");
            lblAnioObligatorio.setVisible(true);
            txtAnio.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        try {
            int anio = Integer.parseInt(anioStr);
            int mes = (Integer) spinnerMes.getValue();
            int dia = (Integer) spinnerDia.getValue();
            LocalDate fecha = LocalDate.of(anio, mes, dia);
            if (fecha.isAfter(LocalDate.now())) {
                lblAnioObligatorio.setText("Fecha futura no válida");
                lblAnioObligatorio.setVisible(true);
                txtAnio.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                return false;
            }
        } catch (Exception e) {
            lblAnioObligatorio.setText("Fecha no válida");
            lblAnioObligatorio.setVisible(true);
            txtAnio.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return false;
        }
        txtAnio.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        lblAnioObligatorio.setVisible(false);
        return true;
    }
    
  
    
    //  validador del formulario
    public boolean validarFormulario() {
        boolean v   = validarTxtIdVoluntario();
        boolean a   = validarTxtIdAnimal();
        boolean r   = validarTxtIdRefugio();
        boolean act = validarActividad();
        boolean f   = validarFecha();
        return v && a && r && act && f;
    }

    // Junta los datos de la fecha
    private LocalDateTime construirFecha() {
        int anio = Integer.parseInt(txtAnio.getText().trim());
        int mes  = (Integer) spinnerMes.getValue();
        int dia  = (Integer) spinnerDia.getValue();
        return LocalDateTime.of(anio, mes, dia, 0, 0);
    }
    
    // Registra la tarea sin antes de aplicar las validaciones a los datos
    private void registrarTarea() {
        try {
            if (!validarFormulario()) {
                JOptionPane.showMessageDialog(this,
                        "No se pudo registrar. Verifique los campos.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            boolean exito = tareaController.agregarTarea(
                    construirFecha(),
                    jTextAreaActividad.getText().trim(),
                    Integer.parseInt(txtIdVoluntario.getText().trim()),
                    Integer.parseInt(txtIdAnimal.getText().trim()),
                    Integer.parseInt(txtIdRefugio.getText().trim())
            );
            if (exito) {
                JOptionPane.showMessageDialog(this, "Tarea registrada correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo guardar la tarea.");
            }
            cargarTareas();
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
        private void actualizar() {
        try {
            if (!validarFormulario()) {
                JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar. Verifique los campos.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int id = Integer.parseInt(txtId.getText().trim());
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Seguro que quieres actualizar esta tarea?",
                    "Confirmar actualización", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                boolean exito = tareaController.actualizarTarea(
                        id,
                        construirFecha(),
                        jTextAreaActividad.getText().trim(),
                        Integer.parseInt(txtIdVoluntario.getText().trim()),
                        Integer.parseInt(txtIdAnimal.getText().trim()),
                        Integer.parseInt(txtIdRefugio.getText().trim())
                );
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Tarea actualizada correctamente.");
                    cargarTareas();
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Ocurrió un error al actualizar la tarea.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        
            private void eliminar() {
        try {
            int id = Integer.parseInt(txtId.getText().trim());
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Seguro que quieres eliminar esta tarea?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                boolean exito = tareaController.eliminarTarea(id);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Tarea eliminada correctamente.");
                    cargarTareas();
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Ocurrió un error al eliminar la tarea.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
       
    
    
private void filtrarTabla(String texto) {
    if (texto.trim().isEmpty()) {
        tblTarea.setModel(tareaController.obtenerTablaTareas());
    } else {
        tblTarea.setModel(tareaController.buscarTablaPorActividad(texto));
    }
}
    
    
    
}
